git追加、起動コメント追加、コンテナ起動テスト修正

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -56,17 +56,21 @@ jobs:
       - name: Test the Docker image
         run: |
           docker run --name test -d -p 9000:8080 -v $PWD/sync:/sync "${IMAGE_IDENTITY}"
-          sleep 3
-          curl -LsS --retry 10 \
-            --retry-delay 3 \
-              http://localhost:9000 \
-            | grep "Grav" \
-            || FAIL=true
+          MAX_RETRY=30
+          n=0
+          SUCCESS=false
+          until [ $n -ge $MAX_RETRY || "$SUCCESS" ]
+          do
+            sleep 3
+            curl --retry 50 -L --retry-delay 3 --head http://localhost:9000 \
+              | grep "HTTP/1.1 200 OK" && SUCCESS=true
+          done
           docker stop test
           docker rm test
-          if [ "$FAIL" = "true" ]
+          if [ "$SUCCESS" != "true" ]
           then
-            echo "container did not start correctly... something wrong..."
+            echo "failed: ${@}" >&2
+            docker logs "${IMAGE_IDENTITY}"
             exit 1
           fi
 
